all: hospitalCharges.out







run: hospitalCharges.out

	./hospitalCharges.out







hospitalCharges.out: hospitalCharges.cpp Patient.cpp 

	g++ -Wall hospitalCharges.cpp Patient.cpp -o hospitalCharges.out











clean:

	rm -f hospitalCharges.out
