all: main.out







run: main.out

	./main.out







main.out: main.cpp Customer.cpp Employee.cpp Invoice.cpp Car.cpp Student.cpp Vehicle.cpp Motorcycle.cpp

	g++ -Wall main.cpp Customer.cpp Employee.cpp Invoice.cpp Car.cpp Student.cpp Vehicle.cpp Motorcycle.cpp -o main.out











clean:

	rm -f main.out
